//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/winauth/WinAuthProtocolClient.java
//

#ifndef _ComUsOpenserverProtocolsWinauthWinAuthProtocolClient_H_
#define _ComUsOpenserverProtocolsWinauthWinAuthProtocolClient_H_

#include "J2ObjC_header.h"
#include "com/us/openserver/protocols/winauth/WinAuthProtocol.h"

@class ComUsOpenserverProtocolsBinaryReader;

#define ComUsOpenserverProtocolsWinauthWinAuthProtocolClient_TIMEOUT 120000

@interface ComUsOpenserverProtocolsWinauthWinAuthProtocolClient : ComUsOpenserverProtocolsWinauthWinAuthProtocol

#pragma mark Public

- (instancetype)init;

- (jboolean)authenticateWithNSString:(NSString *)userName
                        withNSString:(NSString *)password
                        withNSString:(NSString *)domain;

- (void)onPacketReceivedWithComUsOpenserverProtocolsBinaryReader:(ComUsOpenserverProtocolsBinaryReader *)br;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverProtocolsWinauthWinAuthProtocolClient)

J2OBJC_STATIC_FIELD_GETTER(ComUsOpenserverProtocolsWinauthWinAuthProtocolClient, TIMEOUT, jint)

FOUNDATION_EXPORT void ComUsOpenserverProtocolsWinauthWinAuthProtocolClient_init(ComUsOpenserverProtocolsWinauthWinAuthProtocolClient *self);

FOUNDATION_EXPORT ComUsOpenserverProtocolsWinauthWinAuthProtocolClient *new_ComUsOpenserverProtocolsWinauthWinAuthProtocolClient_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverProtocolsWinauthWinAuthProtocolClient)

#endif // _ComUsOpenserverProtocolsWinauthWinAuthProtocolClient_H_
