//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/winauth/WinAuthProtocolCommands.java
//


#include "J2ObjC_source.h"
#include "com/us/openserver/protocols/winauth/WinAuthProtocolCommands.h"

@implementation ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands

- (instancetype)init {
  ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "AUTHENTICATE_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands_AUTHENTICATE },
    { "AUTHENTICATED_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands_AUTHENTICATED },
    { "ACCESS_DENIED_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands_ACCESS_DENIED },
    { "ERROR_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands_ERROR },
  };
  static const J2ObjcClassInfo _ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands = { 2, "WinAuthProtocolCommands", "com.us.openserver.protocols.winauth", NULL, 0x1, 1, methods, 4, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands;
}

@end

void ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands_init(ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands *self) {
  (void) NSObject_init(self);
}

ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands *new_ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands_init() {
  ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands *self = [ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands alloc];
  ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands)
