//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/ILoggerObserver.java
//


#include "J2ObjC_source.h"
#include "com/us/openserver/ILoggerObserver.h"
#include "com/us/openserver/Level.h"

@interface ComUsOpenserverILoggerObserver : NSObject
@end

@implementation ComUsOpenserverILoggerObserver

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onLogMessageWithComUsOpenserverLevelEnum:withNSString:", "onLogMessage", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComUsOpenserverILoggerObserver = { 2, "ILoggerObserver", "com.us.openserver", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComUsOpenserverILoggerObserver;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComUsOpenserverILoggerObserver)
