//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/Level.java
//

#ifndef _ComUsOpenserverLevel_H_
#define _ComUsOpenserverLevel_H_

#include "J2ObjC_header.h"
#include "java/lang/Enum.h"

typedef NS_ENUM(NSUInteger, ComUsOpenserverLevel) {
  ComUsOpenserverLevel_Debug = 0,
  ComUsOpenserverLevel_Info = 1,
  ComUsOpenserverLevel_Notice = 2,
  ComUsOpenserverLevel_Critical = 3,
  ComUsOpenserverLevel_Error = 4,
};

@interface ComUsOpenserverLevelEnum : JavaLangEnum < NSCopying >

#pragma mark Package-Private

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *ComUsOpenserverLevelEnum_values();

+ (ComUsOpenserverLevelEnum *)valueOfWithNSString:(NSString *)name;
FOUNDATION_EXPORT ComUsOpenserverLevelEnum *ComUsOpenserverLevelEnum_valueOfWithNSString_(NSString *name);

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(ComUsOpenserverLevelEnum)

FOUNDATION_EXPORT ComUsOpenserverLevelEnum *ComUsOpenserverLevelEnum_values_[];

#define ComUsOpenserverLevelEnum_Debug ComUsOpenserverLevelEnum_values_[ComUsOpenserverLevel_Debug]
J2OBJC_ENUM_CONSTANT_GETTER(ComUsOpenserverLevelEnum, Debug)

#define ComUsOpenserverLevelEnum_Info ComUsOpenserverLevelEnum_values_[ComUsOpenserverLevel_Info]
J2OBJC_ENUM_CONSTANT_GETTER(ComUsOpenserverLevelEnum, Info)

#define ComUsOpenserverLevelEnum_Notice ComUsOpenserverLevelEnum_values_[ComUsOpenserverLevel_Notice]
J2OBJC_ENUM_CONSTANT_GETTER(ComUsOpenserverLevelEnum, Notice)

#define ComUsOpenserverLevelEnum_Critical ComUsOpenserverLevelEnum_values_[ComUsOpenserverLevel_Critical]
J2OBJC_ENUM_CONSTANT_GETTER(ComUsOpenserverLevelEnum, Critical)

#define ComUsOpenserverLevelEnum_Error ComUsOpenserverLevelEnum_values_[ComUsOpenserverLevel_Error]
J2OBJC_ENUM_CONSTANT_GETTER(ComUsOpenserverLevelEnum, Error)

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverLevelEnum)

#endif // _ComUsOpenserverLevel_H_
