//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/session/PacketHandler.java
//

#ifndef _ComUsOpenserverSessionPacketHandler_H_
#define _ComUsOpenserverSessionPacketHandler_H_

#include "J2ObjC_header.h"
#include "java/lang/Runnable.h"

@class ComUsOpenserverProtocolsBinaryReader;
@class ComUsOpenserverSessionSession;
@class JavaLangException;

@interface ComUsOpenserverSessionPacketHandler : NSObject < JavaLangRunnable >

#pragma mark Public

- (instancetype)initWithComUsOpenserverSessionSession:(ComUsOpenserverSessionSession *)session
             withComUsOpenserverProtocolsBinaryReader:(ComUsOpenserverProtocolsBinaryReader *)br;

- (void)execute;

- (JavaLangException *)getException;

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverSessionPacketHandler)

FOUNDATION_EXPORT void ComUsOpenserverSessionPacketHandler_initWithComUsOpenserverSessionSession_withComUsOpenserverProtocolsBinaryReader_(ComUsOpenserverSessionPacketHandler *self, ComUsOpenserverSessionSession *session, ComUsOpenserverProtocolsBinaryReader *br);

FOUNDATION_EXPORT ComUsOpenserverSessionPacketHandler *new_ComUsOpenserverSessionPacketHandler_initWithComUsOpenserverSessionSession_withComUsOpenserverProtocolsBinaryReader_(ComUsOpenserverSessionSession *session, ComUsOpenserverProtocolsBinaryReader *br) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverSessionPacketHandler)

#endif // _ComUsOpenserverSessionPacketHandler_H_
