//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/AuthenticationProtocolBase.java
//

#ifndef _ComUsOpenserverProtocolsAuthenticationProtocolBase_H_
#define _ComUsOpenserverProtocolsAuthenticationProtocolBase_H_

#include "J2ObjC_header.h"
#include "ProtocolBase.h"

@interface ComUsOpenserverProtocolsAuthenticationProtocolBase : ComUsOpenserverProtocolsProtocolBase {
 @public
  jboolean isAuthenticated_;
  NSString *userName_;
}

#pragma mark Public

- (instancetype)init;

- (jboolean)getIsAuthenticated;

- (NSString *)getUserName;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverProtocolsAuthenticationProtocolBase)

J2OBJC_FIELD_SETTER(ComUsOpenserverProtocolsAuthenticationProtocolBase, userName_, NSString *)

FOUNDATION_EXPORT void ComUsOpenserverProtocolsAuthenticationProtocolBase_init(ComUsOpenserverProtocolsAuthenticationProtocolBase *self);

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverProtocolsAuthenticationProtocolBase)

#endif // _ComUsOpenserverProtocolsAuthenticationProtocolBase_H_
