//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/Client.java
//

#include "J2ObjC_header.h"

#pragma push_macro("Client_INCLUDE_ALL")
#ifdef Client_RESTRICT
#define Client_INCLUDE_ALL 0
#else
#define Client_INCLUDE_ALL 1
#endif
#undef Client_RESTRICT

#if !defined (ComUsOpenserverClient_) && (Client_INCLUDE_ALL || defined(ComUsOpenserverClient_INCLUDE))
#define ComUsOpenserverClient_

@class ComUsOpenserverConfigurationServerConfiguration;
@class ComUsOpenserverLogger;
@class ComUsOpenserverProtocolsProtocolBase;
@class ComUsOpenserverSessionSession;
@class IOSIntArray;
@class JavaLangException;
@class JavaUtilHashMap;
@protocol ComUsOpenserverIClientObserver;

@interface ComUsOpenserverClient : NSObject

#pragma mark Public

- (instancetype)initWithComUsOpenserverIClientObserver:(id<ComUsOpenserverIClientObserver>)clientObserver
   withComUsOpenserverConfigurationServerConfiguration:(ComUsOpenserverConfigurationServerConfiguration *)serverConfiguration
                                   withJavaUtilHashMap:(JavaUtilHashMap *)protocolConfigurations;

- (instancetype)initWithComUsOpenserverIClientObserver:(id<ComUsOpenserverIClientObserver>)clientObserver
   withComUsOpenserverConfigurationServerConfiguration:(ComUsOpenserverConfigurationServerConfiguration *)serverConfiguration
                                   withJavaUtilHashMap:(JavaUtilHashMap *)protocolConfigurations
                             withComUsOpenserverLogger:(ComUsOpenserverLogger *)logger;

- (instancetype)initWithComUsOpenserverIClientObserver:(id<ComUsOpenserverIClientObserver>)clientObserver
   withComUsOpenserverConfigurationServerConfiguration:(ComUsOpenserverConfigurationServerConfiguration *)serverConfiguration
                                   withJavaUtilHashMap:(JavaUtilHashMap *)protocolConfigurations
                             withComUsOpenserverLogger:(ComUsOpenserverLogger *)logger
                                                withId:(id)userData;

- (void)close;

- (void)closeWithInt:(jint)protocolId;

- (void)closeBackgroundThread;

- (void)closeBackgroundThreadWithInt:(jint)protocolId;

- (void)connect;

- (void)connectBackgroundThread;

- (jboolean)getIsConnected;

- (ComUsOpenserverLogger *)getLogger;

- (JavaUtilHashMap *)getProtocolConfigurations;

- (ComUsOpenserverConfigurationServerConfiguration *)getServerConfiguration;

- (IOSIntArray *)getServerSupportedProtocolIds;

- (ComUsOpenserverSessionSession *)getSession;

- (id)getUserData;

- (ComUsOpenserverProtocolsProtocolBase *)initialize__WithInt:(jint)protocolId OBJC_METHOD_FAMILY_NONE;

- (void)onConnectionLostWithJavaLangException:(JavaLangException *)ex;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverClient)

FOUNDATION_EXPORT void ComUsOpenserverClient_initWithComUsOpenserverIClientObserver_withComUsOpenserverConfigurationServerConfiguration_withJavaUtilHashMap_(ComUsOpenserverClient *self, id<ComUsOpenserverIClientObserver> clientObserver, ComUsOpenserverConfigurationServerConfiguration *serverConfiguration, JavaUtilHashMap *protocolConfigurations);

FOUNDATION_EXPORT ComUsOpenserverClient *new_ComUsOpenserverClient_initWithComUsOpenserverIClientObserver_withComUsOpenserverConfigurationServerConfiguration_withJavaUtilHashMap_(id<ComUsOpenserverIClientObserver> clientObserver, ComUsOpenserverConfigurationServerConfiguration *serverConfiguration, JavaUtilHashMap *protocolConfigurations) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComUsOpenserverClient *create_ComUsOpenserverClient_initWithComUsOpenserverIClientObserver_withComUsOpenserverConfigurationServerConfiguration_withJavaUtilHashMap_(id<ComUsOpenserverIClientObserver> clientObserver, ComUsOpenserverConfigurationServerConfiguration *serverConfiguration, JavaUtilHashMap *protocolConfigurations);

FOUNDATION_EXPORT void ComUsOpenserverClient_initWithComUsOpenserverIClientObserver_withComUsOpenserverConfigurationServerConfiguration_withJavaUtilHashMap_withComUsOpenserverLogger_(ComUsOpenserverClient *self, id<ComUsOpenserverIClientObserver> clientObserver, ComUsOpenserverConfigurationServerConfiguration *serverConfiguration, JavaUtilHashMap *protocolConfigurations, ComUsOpenserverLogger *logger);

FOUNDATION_EXPORT ComUsOpenserverClient *new_ComUsOpenserverClient_initWithComUsOpenserverIClientObserver_withComUsOpenserverConfigurationServerConfiguration_withJavaUtilHashMap_withComUsOpenserverLogger_(id<ComUsOpenserverIClientObserver> clientObserver, ComUsOpenserverConfigurationServerConfiguration *serverConfiguration, JavaUtilHashMap *protocolConfigurations, ComUsOpenserverLogger *logger) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComUsOpenserverClient *create_ComUsOpenserverClient_initWithComUsOpenserverIClientObserver_withComUsOpenserverConfigurationServerConfiguration_withJavaUtilHashMap_withComUsOpenserverLogger_(id<ComUsOpenserverIClientObserver> clientObserver, ComUsOpenserverConfigurationServerConfiguration *serverConfiguration, JavaUtilHashMap *protocolConfigurations, ComUsOpenserverLogger *logger);

FOUNDATION_EXPORT void ComUsOpenserverClient_initWithComUsOpenserverIClientObserver_withComUsOpenserverConfigurationServerConfiguration_withJavaUtilHashMap_withComUsOpenserverLogger_withId_(ComUsOpenserverClient *self, id<ComUsOpenserverIClientObserver> clientObserver, ComUsOpenserverConfigurationServerConfiguration *serverConfiguration, JavaUtilHashMap *protocolConfigurations, ComUsOpenserverLogger *logger, id userData);

FOUNDATION_EXPORT ComUsOpenserverClient *new_ComUsOpenserverClient_initWithComUsOpenserverIClientObserver_withComUsOpenserverConfigurationServerConfiguration_withJavaUtilHashMap_withComUsOpenserverLogger_withId_(id<ComUsOpenserverIClientObserver> clientObserver, ComUsOpenserverConfigurationServerConfiguration *serverConfiguration, JavaUtilHashMap *protocolConfigurations, ComUsOpenserverLogger *logger, id userData) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComUsOpenserverClient *create_ComUsOpenserverClient_initWithComUsOpenserverIClientObserver_withComUsOpenserverConfigurationServerConfiguration_withJavaUtilHashMap_withComUsOpenserverLogger_withId_(id<ComUsOpenserverIClientObserver> clientObserver, ComUsOpenserverConfigurationServerConfiguration *serverConfiguration, JavaUtilHashMap *protocolConfigurations, ComUsOpenserverLogger *logger, id userData);

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverClient)

#endif

#pragma pop_macro("Client_INCLUDE_ALL")
