//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/databaseauth/DatabaseAuthProtocolClient.java
//

#include "J2ObjC_header.h"

#pragma push_macro("DatabaseAuthProtocolClient_INCLUDE_ALL")
#ifdef DatabaseAuthProtocolClient_RESTRICT
#define DatabaseAuthProtocolClient_INCLUDE_ALL 0
#else
#define DatabaseAuthProtocolClient_INCLUDE_ALL 1
#endif
#undef DatabaseAuthProtocolClient_RESTRICT

#if !defined (ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolClient_) && (DatabaseAuthProtocolClient_INCLUDE_ALL || defined(ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolClient_INCLUDE))
#define ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolClient_

#define DatabaseAuthProtocol_RESTRICT 1
#define ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol_INCLUDE 1
#include "DatabaseAuthProtocol.h"

@class ComUsOpenserverProtocolsBinaryReader;

@interface ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolClient : ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol

#pragma mark Public

- (instancetype)init;

- (jboolean)authenticateWithNSString:(NSString *)userName
                        withNSString:(NSString *)password;

- (jboolean)authenticateBGWithNSString:(NSString *)userName
                          withNSString:(NSString *)password;

- (void)onPacketReceivedWithComUsOpenserverProtocolsBinaryReader:(ComUsOpenserverProtocolsBinaryReader *)br;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolClient)

inline jint ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolClient_get_TIMEOUT();
#define ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolClient_TIMEOUT 120000
J2OBJC_STATIC_FIELD_CONSTANT(ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolClient, TIMEOUT, jint)

FOUNDATION_EXPORT void ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolClient_init(ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolClient *self);

FOUNDATION_EXPORT ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolClient *new_ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolClient_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolClient *create_ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolClient_init();

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolClient)

#endif

#pragma pop_macro("DatabaseAuthProtocolClient_INCLUDE_ALL")
