//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/IClientObserver.java
//

#include "IClientObserver.h"
#include "J2ObjC_source.h"
#include "java/lang/Exception.h"

@interface ComUsOpenserverIClientObserver : NSObject

@end

@implementation ComUsOpenserverIClientObserver

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onConnectionLostWithJavaLangException:", "onConnectionLost", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComUsOpenserverIClientObserver = { 2, "IClientObserver", "com.us.openserver", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComUsOpenserverIClientObserver;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComUsOpenserverIClientObserver)
