//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/hello/IHelloProtocolObserver.java
//

#include "J2ObjC_header.h"

#pragma push_macro("IHelloProtocolObserver_INCLUDE_ALL")
#ifdef IHelloProtocolObserver_RESTRICT
#define IHelloProtocolObserver_INCLUDE_ALL 0
#else
#define IHelloProtocolObserver_INCLUDE_ALL 1
#endif
#undef IHelloProtocolObserver_RESTRICT

#if !defined (ComUsOpenserverProtocolsHelloIHelloProtocolObserver_) && (IHelloProtocolObserver_INCLUDE_ALL || defined(ComUsOpenserverProtocolsHelloIHelloProtocolObserver_INCLUDE))
#define ComUsOpenserverProtocolsHelloIHelloProtocolObserver_

@protocol ComUsOpenserverProtocolsHelloIHelloProtocolObserver < NSObject, JavaObject >

- (void)onHelloCompleteWithNSString:(NSString *)serverResponse;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverProtocolsHelloIHelloProtocolObserver)

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverProtocolsHelloIHelloProtocolObserver)

#endif

#pragma pop_macro("IHelloProtocolObserver_INCLUDE_ALL")
