//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/hello/IHelloProtocolObserver.java
//

#include "IHelloProtocolObserver.h"
#include "J2ObjC_source.h"

@interface ComUsOpenserverProtocolsHelloIHelloProtocolObserver : NSObject

@end

@implementation ComUsOpenserverProtocolsHelloIHelloProtocolObserver

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onHelloCompleteWithNSString:", "onHelloComplete", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComUsOpenserverProtocolsHelloIHelloProtocolObserver = { 2, "IHelloProtocolObserver", "com.us.openserver.protocols.hello", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComUsOpenserverProtocolsHelloIHelloProtocolObserver;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComUsOpenserverProtocolsHelloIHelloProtocolObserver)
