//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/hello/IHelloProtocolObserver.java
//

#ifndef _ComUsOpenserverProtocolsHelloIHelloProtocolObserver_H_
#define _ComUsOpenserverProtocolsHelloIHelloProtocolObserver_H_

#include "J2ObjC_header.h"

@protocol ComUsOpenserverProtocolsHelloIHelloProtocolObserver < NSObject, JavaObject >

- (void)onHelloCompleteWithNSString:(NSString *)serverResponse;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverProtocolsHelloIHelloProtocolObserver)

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverProtocolsHelloIHelloProtocolObserver)

#endif // _ComUsOpenserverProtocolsHelloIHelloProtocolObserver_H_
