//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/ILoggerObserver.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ILoggerObserver_INCLUDE_ALL")
#ifdef ILoggerObserver_RESTRICT
#define ILoggerObserver_INCLUDE_ALL 0
#else
#define ILoggerObserver_INCLUDE_ALL 1
#endif
#undef ILoggerObserver_RESTRICT

#if !defined (ComUsOpenserverILoggerObserver_) && (ILoggerObserver_INCLUDE_ALL || defined(ComUsOpenserverILoggerObserver_INCLUDE))
#define ComUsOpenserverILoggerObserver_

@class ComUsOpenserverLevel;

@protocol ComUsOpenserverILoggerObserver < NSObject, JavaObject >

- (void)onLogMessageWithComUsOpenserverLevel:(ComUsOpenserverLevel *)level
                                withNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverILoggerObserver)

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverILoggerObserver)

#endif

#pragma pop_macro("ILoggerObserver_INCLUDE_ALL")
