//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/session/PacketReadTypes.java
//

#ifndef _ComUsOpenserverSessionPacketReadTypes_H_
#define _ComUsOpenserverSessionPacketReadTypes_H_

#include "J2ObjC_header.h"

#define ComUsOpenserverSessionPacketReadTypes_Header 0
#define ComUsOpenserverSessionPacketReadTypes_HeaderComplete 1
#define ComUsOpenserverSessionPacketReadTypes_Payload 2

@interface ComUsOpenserverSessionPacketReadTypes : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverSessionPacketReadTypes)

J2OBJC_STATIC_FIELD_GETTER(ComUsOpenserverSessionPacketReadTypes, Header, jbyte)

J2OBJC_STATIC_FIELD_GETTER(ComUsOpenserverSessionPacketReadTypes, HeaderComplete, jbyte)

J2OBJC_STATIC_FIELD_GETTER(ComUsOpenserverSessionPacketReadTypes, Payload, jbyte)

FOUNDATION_EXPORT void ComUsOpenserverSessionPacketReadTypes_init(ComUsOpenserverSessionPacketReadTypes *self);

FOUNDATION_EXPORT ComUsOpenserverSessionPacketReadTypes *new_ComUsOpenserverSessionPacketReadTypes_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverSessionPacketReadTypes)

#endif // _ComUsOpenserverSessionPacketReadTypes_H_
