//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/PacketWriter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("PacketWriter_INCLUDE_ALL")
#ifdef PacketWriter_RESTRICT
#define PacketWriter_INCLUDE_ALL 0
#else
#define PacketWriter_INCLUDE_ALL 1
#endif
#undef PacketWriter_RESTRICT

#if !defined (ComUsOpenserverProtocolsPacketWriter_) && (PacketWriter_INCLUDE_ALL || defined(ComUsOpenserverProtocolsPacketWriter_INCLUDE))
#define ComUsOpenserverProtocolsPacketWriter_

#define JavaLangRunnable_RESTRICT 1
#define JavaLangRunnable_INCLUDE 1
#include "java/lang/Runnable.h"

@class ComUsOpenserverSessionSession;
@class IOSByteArray;
@class JavaLangException;

@interface ComUsOpenserverProtocolsPacketWriter : NSObject < JavaLangRunnable >

#pragma mark Public

- (instancetype)initWithComUsOpenserverSessionSession:(ComUsOpenserverSessionSession *)session
                                        withByteArray:(IOSByteArray *)packet;

- (void)execute;

- (JavaLangException *)getException;

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverProtocolsPacketWriter)

FOUNDATION_EXPORT void ComUsOpenserverProtocolsPacketWriter_initWithComUsOpenserverSessionSession_withByteArray_(ComUsOpenserverProtocolsPacketWriter *self, ComUsOpenserverSessionSession *session, IOSByteArray *packet);

FOUNDATION_EXPORT ComUsOpenserverProtocolsPacketWriter *new_ComUsOpenserverProtocolsPacketWriter_initWithComUsOpenserverSessionSession_withByteArray_(ComUsOpenserverSessionSession *session, IOSByteArray *packet) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComUsOpenserverProtocolsPacketWriter *create_ComUsOpenserverProtocolsPacketWriter_initWithComUsOpenserverSessionSession_withByteArray_(ComUsOpenserverSessionSession *session, IOSByteArray *packet);

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverProtocolsPacketWriter)

#endif

#pragma pop_macro("PacketWriter_INCLUDE_ALL")
