//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/ProtocolConfiguration.java
//


#include "J2ObjC_source.h"
#include "ProtocolConfiguration.h"

@interface ComUsOpenserverProtocolsProtocolConfiguration () {
 @public
  jint id__;
  NSString *classPath_;
}

@end

J2OBJC_FIELD_SETTER(ComUsOpenserverProtocolsProtocolConfiguration, classPath_, NSString *)

@implementation ComUsOpenserverProtocolsProtocolConfiguration

- (instancetype)init {
  ComUsOpenserverProtocolsProtocolConfiguration_init(self);
  return self;
}

- (instancetype)initWithInt:(jint)id_
               withNSString:(NSString *)classPath {
  ComUsOpenserverProtocolsProtocolConfiguration_initWithInt_withNSString_(self, id_, classPath);
  return self;
}

- (jint)getId {
  return id__;
}

- (void)setIdWithInt:(jint)id_ {
  self->id__ = id_;
}

- (NSString *)getClassPath {
  return classPath_;
}

- (void)setClassPathWithNSString:(NSString *)classPath {
  self->classPath_ = classPath;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "ProtocolConfiguration", NULL, 0x4, NULL, NULL },
    { "initWithInt:withNSString:", "ProtocolConfiguration", NULL, 0x1, NULL, NULL },
    { "getId", NULL, "I", 0x1, NULL, NULL },
    { "setIdWithInt:", "setId", "V", 0x1, NULL, NULL },
    { "getClassPath", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "setClassPathWithNSString:", "setClassPath", "V", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "id__", "id", 0x2, "I", NULL, NULL,  },
    { "classPath_", NULL, 0x2, "Ljava.lang.String;", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _ComUsOpenserverProtocolsProtocolConfiguration = { 2, "ProtocolConfiguration", "com.us.openserver.protocols", NULL, 0x1, 6, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComUsOpenserverProtocolsProtocolConfiguration;
}

@end

void ComUsOpenserverProtocolsProtocolConfiguration_init(ComUsOpenserverProtocolsProtocolConfiguration *self) {
  (void) NSObject_init(self);
}

ComUsOpenserverProtocolsProtocolConfiguration *new_ComUsOpenserverProtocolsProtocolConfiguration_init() {
  ComUsOpenserverProtocolsProtocolConfiguration *self = [ComUsOpenserverProtocolsProtocolConfiguration alloc];
  ComUsOpenserverProtocolsProtocolConfiguration_init(self);
  return self;
}

void ComUsOpenserverProtocolsProtocolConfiguration_initWithInt_withNSString_(ComUsOpenserverProtocolsProtocolConfiguration *self, jint id_, NSString *classPath) {
  (void) ComUsOpenserverProtocolsProtocolConfiguration_init(self);
  self->id__ = id_;
  self->classPath_ = classPath;
}

ComUsOpenserverProtocolsProtocolConfiguration *new_ComUsOpenserverProtocolsProtocolConfiguration_initWithInt_withNSString_(jint id_, NSString *classPath) {
  ComUsOpenserverProtocolsProtocolConfiguration *self = [ComUsOpenserverProtocolsProtocolConfiguration alloc];
  ComUsOpenserverProtocolsProtocolConfiguration_initWithInt_withNSString_(self, id_, classPath);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComUsOpenserverProtocolsProtocolConfiguration)
