//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/configuration/ServerConfiguration.java
//

#ifndef _ComUsOpenserverConfigurationServerConfiguration_H_
#define _ComUsOpenserverConfigurationServerConfiguration_H_

#include "J2ObjC_header.h"

@class ComUsOpenserverConfigurationTlsConfiguration;

@interface ComUsOpenserverConfigurationServerConfiguration : NSObject

#pragma mark Public

- (instancetype)init;

- (NSString *)getHost;

- (jint)getIdleTimeout;

- (jint)getIdleTimeoutInTicks;

- (jint)getPort;

- (jint)getSocketTimeout;

- (jint)getSocketTimeoutInTicks;

- (ComUsOpenserverConfigurationTlsConfiguration *)getTlsConfiguration;

- (void)setHostWithNSString:(NSString *)value;

- (void)setIdleTimeoutWithInt:(jint)value;

- (void)setPortWithInt:(jint)value;

- (void)setSocketTimeoutWithInt:(jint)value;

- (void)setTlsConfigurationWithComUsOpenserverConfigurationTlsConfiguration:(ComUsOpenserverConfigurationTlsConfiguration *)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverConfigurationServerConfiguration)

FOUNDATION_EXPORT void ComUsOpenserverConfigurationServerConfiguration_init(ComUsOpenserverConfigurationServerConfiguration *self);

FOUNDATION_EXPORT ComUsOpenserverConfigurationServerConfiguration *new_ComUsOpenserverConfigurationServerConfiguration_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverConfigurationServerConfiguration)

#endif // _ComUsOpenserverConfigurationServerConfiguration_H_
