//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/session/SessionCloser.java
//


#include "J2ObjC_source.h"
#include "Session.h"
#include "SessionCloser.h"
#include "java/lang/Exception.h"
#include "java/lang/Thread.h"

@interface ComUsOpenserverSessionSessionCloser () {
 @public
  ComUsOpenserverSessionSession *session_;
  jint protocolId_;
}

@end

J2OBJC_FIELD_SETTER(ComUsOpenserverSessionSessionCloser, session_, ComUsOpenserverSessionSession *)

static jint ComUsOpenserverSessionSessionCloser_id__;
J2OBJC_STATIC_FIELD_GETTER(ComUsOpenserverSessionSessionCloser, id__, jint)
J2OBJC_STATIC_FIELD_REF_GETTER(ComUsOpenserverSessionSessionCloser, id__, jint)

@implementation ComUsOpenserverSessionSessionCloser

- (instancetype)initWithComUsOpenserverSessionSession:(ComUsOpenserverSessionSession *)session {
  ComUsOpenserverSessionSessionCloser_initWithComUsOpenserverSessionSession_(self, session);
  return self;
}

- (void)close {
  [self closeWithInt:0];
}

- (void)closeWithInt:(jint)protocolId {
  @try {
    if (protocolId > 0) [((ComUsOpenserverSessionSession *) nil_chk(session_)) closeWithInt:protocolId];
    else [((ComUsOpenserverSessionSession *) nil_chk(session_)) close];
  }
  @catch (JavaLangException *ex) {
  }
}

- (void)closeAsync {
  [self closeAsyncWithInt:0];
}

- (void)closeAsyncWithInt:(jint)protocolId {
  self->protocolId_ = protocolId;
  JavaLangThread *t = new_JavaLangThread_initWithJavaLangRunnable_withNSString_(self, JreStrcat("$I", @"SessionCloser", ++ComUsOpenserverSessionSessionCloser_id__));
  [t start];
}

- (void)run {
  [self closeWithInt:protocolId_];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComUsOpenserverSessionSession:", "SessionCloser", NULL, 0x1, NULL, NULL },
    { "close", NULL, "V", 0x1, NULL, NULL },
    { "closeWithInt:", "close", "V", 0x1, NULL, NULL },
    { "closeAsync", NULL, "V", 0x1, NULL, NULL },
    { "closeAsyncWithInt:", "closeAsync", "V", 0x1, NULL, NULL },
    { "run", NULL, "V", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "session_", NULL, 0x2, "Lcom.us.openserver.session.Session;", NULL, NULL,  },
    { "protocolId_", NULL, 0x2, "I", NULL, NULL,  },
    { "id__", "id", 0xa, "I", &ComUsOpenserverSessionSessionCloser_id__, NULL,  },
  };
  static const J2ObjcClassInfo _ComUsOpenserverSessionSessionCloser = { 2, "SessionCloser", "com.us.openserver.session", NULL, 0x1, 6, methods, 3, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComUsOpenserverSessionSessionCloser;
}

@end

void ComUsOpenserverSessionSessionCloser_initWithComUsOpenserverSessionSession_(ComUsOpenserverSessionSessionCloser *self, ComUsOpenserverSessionSession *session) {
  (void) NSObject_init(self);
  self->session_ = session;
}

ComUsOpenserverSessionSessionCloser *new_ComUsOpenserverSessionSessionCloser_initWithComUsOpenserverSessionSession_(ComUsOpenserverSessionSession *session) {
  ComUsOpenserverSessionSessionCloser *self = [ComUsOpenserverSessionSessionCloser alloc];
  ComUsOpenserverSessionSessionCloser_initWithComUsOpenserverSessionSession_(self, session);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComUsOpenserverSessionSessionCloser)
