//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/session/SessionCloser.java
//

#ifndef _ComUsOpenserverSessionSessionCloser_H_
#define _ComUsOpenserverSessionSessionCloser_H_

#include "J2ObjC_header.h"
#include "java/lang/Runnable.h"

@class ComUsOpenserverSessionSession;

@interface ComUsOpenserverSessionSessionCloser : NSObject < JavaLangRunnable >

#pragma mark Public

- (instancetype)initWithComUsOpenserverSessionSession:(ComUsOpenserverSessionSession *)session;

- (void)close;

- (void)closeWithInt:(jint)protocolId;

- (void)closeBackgroundThread;

- (void)closeBackgroundThreadWithInt:(jint)protocolId;

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverSessionSessionCloser)

FOUNDATION_EXPORT void ComUsOpenserverSessionSessionCloser_initWithComUsOpenserverSessionSession_(ComUsOpenserverSessionSessionCloser *self, ComUsOpenserverSessionSession *session);

FOUNDATION_EXPORT ComUsOpenserverSessionSessionCloser *new_ComUsOpenserverSessionSessionCloser_initWithComUsOpenserverSessionSession_(ComUsOpenserverSessionSession *session) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverSessionSessionCloser)

#endif // _ComUsOpenserverSessionSessionCloser_H_
