//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/session/SessionInitializer.java
//

#ifndef _ComUsOpenserverSessionSessionInitializer_H_
#define _ComUsOpenserverSessionSessionInitializer_H_

#include "J2ObjC_header.h"
#include "java/lang/Runnable.h"

@class ComUsOpenserverClient;
@class ComUsOpenserverProtocolsProtocolBase;

@interface ComUsOpenserverSessionSessionInitializer : NSObject < JavaLangRunnable >

#pragma mark Public

- (instancetype)initWithComUsOpenserverClient:(ComUsOpenserverClient *)client
                                      withInt:(jint)protocolId;

- (ComUsOpenserverProtocolsProtocolBase *)initialize__WithInt:(jint)protocolId OBJC_METHOD_FAMILY_NONE;

- (ComUsOpenserverProtocolsProtocolBase *)initializeAsync OBJC_METHOD_FAMILY_NONE;

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverSessionSessionInitializer)

FOUNDATION_EXPORT void ComUsOpenserverSessionSessionInitializer_initWithComUsOpenserverClient_withInt_(ComUsOpenserverSessionSessionInitializer *self, ComUsOpenserverClient *client, jint protocolId);

FOUNDATION_EXPORT ComUsOpenserverSessionSessionInitializer *new_ComUsOpenserverSessionSessionInitializer_initWithComUsOpenserverClient_withInt_(ComUsOpenserverClient *client, jint protocolId) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverSessionSessionInitializer)

#endif // _ComUsOpenserverSessionSessionInitializer_H_
