//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/configuration/TlsConfiguration.java
//

#include "J2ObjC_header.h"

#pragma push_macro("TlsConfiguration_INCLUDE_ALL")
#ifdef TlsConfiguration_RESTRICT
#define TlsConfiguration_INCLUDE_ALL 0
#else
#define TlsConfiguration_INCLUDE_ALL 1
#endif
#undef TlsConfiguration_RESTRICT

#if !defined (ComUsOpenserverConfigurationTlsConfiguration_) && (TlsConfiguration_INCLUDE_ALL || defined(ComUsOpenserverConfigurationTlsConfiguration_INCLUDE))
#define ComUsOpenserverConfigurationTlsConfiguration_

@interface ComUsOpenserverConfigurationTlsConfiguration : NSObject

#pragma mark Public

- (instancetype)init;

- (jboolean)getAllowCertificateChainErrors;

- (jboolean)getAllowSelfSignedCertificate;

- (NSString *)getCertificate;

- (jboolean)getCheckCertificateRevocation;

- (jboolean)getRequireRemoteCertificate;

- (jboolean)isEnabled;

- (void)setAllowCertificateChainErrorsWithBoolean:(jboolean)value;

- (void)setAllowSelfSignedCertificateWithBoolean:(jboolean)value;

- (void)setCertificateWithNSString:(NSString *)value;

- (void)setCheckCertificateRevocationWithBoolean:(jboolean)value;

- (void)setEnabledWithBoolean:(jboolean)value;

- (void)setRequireRemoteCertificateWithBoolean:(jboolean)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverConfigurationTlsConfiguration)

FOUNDATION_EXPORT void ComUsOpenserverConfigurationTlsConfiguration_init(ComUsOpenserverConfigurationTlsConfiguration *self);

FOUNDATION_EXPORT ComUsOpenserverConfigurationTlsConfiguration *new_ComUsOpenserverConfigurationTlsConfiguration_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComUsOpenserverConfigurationTlsConfiguration *create_ComUsOpenserverConfigurationTlsConfiguration_init();

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverConfigurationTlsConfiguration)

#endif

#pragma pop_macro("TlsConfiguration_INCLUDE_ALL")
