//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/winauth/WinAuthProtocolClient.java
//


#include "BinaryReader.h"
#include "BinaryWriter.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "Level.h"
#include "PacketWriter.h"
#include "Session.h"
#include "WinAuthProtocol.h"
#include "WinAuthProtocolClient.h"
#include "WinAuthProtocolCommands.h"
#include "java/io/IOException.h"
#include "java/lang/Integer.h"
#include "java/lang/InterruptedException.h"

@implementation ComUsOpenserverProtocolsWinauthWinAuthProtocolClient

- (instancetype)init {
  ComUsOpenserverProtocolsWinauthWinAuthProtocolClient_init(self);
  return self;
}

- (jboolean)authenticateWithNSString:(NSString *)userName
                        withNSString:(NSString *)password
                        withNSString:(NSString *)domain {
  @synchronized(self) {
    if (session_ == nil) return NO;
    userName_ = userName;
    ((ComUsOpenserverSessionSession *) nil_chk(session_))->UserName_ = userName;
    ComUsOpenserverProtocolsBinaryWriter *bw = new_ComUsOpenserverProtocolsBinaryWriter_init();
    @try {
      [bw writeUInt16WithInt:ComUsOpenserverProtocolsWinauthWinAuthProtocol_PROTOCOL_IDENTIFIER];
      [bw writeWithInt:(jbyte) ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands_AUTHENTICATE];
      [bw writeStringWithNSString:userName];
      [bw writeStringWithNSString:password];
      [bw writeStringWithNSString:domain];
      ComUsOpenserverProtocolsPacketWriter *pw = new_ComUsOpenserverProtocolsPacketWriter_initWithComUsOpenserverSessionSession_withByteArray_(session_, [bw toByteArray]);
      [pw execute];
    }
    @finally {
      @try {
        [bw close];
      }
      @catch (JavaIoIOException *ex) {
      }
    }
    @try {
      [self waitWithLong:ComUsOpenserverProtocolsWinauthWinAuthProtocolClient_TIMEOUT];
    }
    @catch (JavaLangInterruptedException *ex) {
    }
    return isAuthenticated_;
  }
}

- (void)onPacketReceivedWithComUsOpenserverProtocolsBinaryReader:(ComUsOpenserverProtocolsBinaryReader *)br {
  @synchronized(self) {
    if (session_ == nil) return;
    jint command = [((ComUsOpenserverProtocolsBinaryReader *) nil_chk(br)) readByte];
    switch (command) {
      case ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands_AUTHENTICATED:
      isAuthenticated_ = YES;
      ((ComUsOpenserverSessionSession *) nil_chk(session_))->IsAuthenticated_ = YES;
      [self logWithComUsOpenserverLevelEnum:ComUsOpenserverLevelEnum_get_Info() withNSString:@"Authenticated."];
      [self notifyAll];
      break;
      case ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands_ACCESS_DENIED:
      [self logWithComUsOpenserverLevelEnum:ComUsOpenserverLevelEnum_get_Notice() withNSString:@"Access denied."];
      [self notifyAll];
      break;
      case ComUsOpenserverProtocolsWinauthWinAuthProtocolCommands_ERROR:
      {
        @try {
          NSString *errorMessage = [br readString];
          [self logWithComUsOpenserverLevelEnum:ComUsOpenserverLevelEnum_get_Notice() withNSString:errorMessage];
        }
        @catch (JavaIoIOException *ex) {
        }
        [self notifyAll];
        break;
      }
      default:
      [self logWithComUsOpenserverLevelEnum:ComUsOpenserverLevelEnum_get_Error() withNSString:NSString_formatWithNSString_withNSObjectArray_(@"Invalid or unsupported command.  Command: %1$s", [IOSObjectArray newArrayWithObjects:(id[]){ JavaLangInteger_valueOfWithInt_(command) } count:1 type:NSObject_class_()])];
      break;
    }
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "WinAuthProtocolClient", NULL, 0x1, NULL, NULL },
    { "authenticateWithNSString:withNSString:withNSString:", "authenticate", "Z", 0x1, NULL, NULL },
    { "onPacketReceivedWithComUsOpenserverProtocolsBinaryReader:", "onPacketReceived", "V", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "TIMEOUT_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = ComUsOpenserverProtocolsWinauthWinAuthProtocolClient_TIMEOUT },
  };
  static const J2ObjcClassInfo _ComUsOpenserverProtocolsWinauthWinAuthProtocolClient = { 2, "WinAuthProtocolClient", "com.us.openserver.protocols.winauth", NULL, 0x1, 3, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComUsOpenserverProtocolsWinauthWinAuthProtocolClient;
}

@end

void ComUsOpenserverProtocolsWinauthWinAuthProtocolClient_init(ComUsOpenserverProtocolsWinauthWinAuthProtocolClient *self) {
  (void) ComUsOpenserverProtocolsWinauthWinAuthProtocol_init(self);
}

ComUsOpenserverProtocolsWinauthWinAuthProtocolClient *new_ComUsOpenserverProtocolsWinauthWinAuthProtocolClient_init() {
  ComUsOpenserverProtocolsWinauthWinAuthProtocolClient *self = [ComUsOpenserverProtocolsWinauthWinAuthProtocolClient alloc];
  ComUsOpenserverProtocolsWinauthWinAuthProtocolClient_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComUsOpenserverProtocolsWinauthWinAuthProtocolClient)
