//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/BinaryWriter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("BinaryWriter_INCLUDE_ALL")
#ifdef BinaryWriter_RESTRICT
#define BinaryWriter_INCLUDE_ALL 0
#else
#define BinaryWriter_INCLUDE_ALL 1
#endif
#undef BinaryWriter_RESTRICT

#if !defined (ComUsOpenserverProtocolsBinaryWriter_) && (BinaryWriter_INCLUDE_ALL || defined(ComUsOpenserverProtocolsBinaryWriter_INCLUDE))
#define ComUsOpenserverProtocolsBinaryWriter_

#define JavaIoByteArrayOutputStream_RESTRICT 1
#define JavaIoByteArrayOutputStream_INCLUDE 1
#include "java/io/ByteArrayOutputStream.h"

@class IOSByteArray;
@class IOSIntArray;
@class JavaLangLong;
@class JavaMathBigDecimal;
@class JavaUtilDate;

@interface ComUsOpenserverProtocolsBinaryWriter : JavaIoByteArrayOutputStream

#pragma mark Public

- (instancetype)init;

- (void)writeWithJavaMathBigDecimal:(JavaMathBigDecimal *)value;

- (void)writeWithBoolean:(jboolean)value;

- (void)writeWithJavaUtilDate:(JavaUtilDate *)date;

- (void)writeWithIntArray:(IOSIntArray *)value;

- (void)writeWithLong:(jlong)value;

- (void)writeBytesWithByteArray:(IOSByteArray *)value;

- (void)writeIntWithInt:(jint)value;

- (void)writeInt16WithShort:(jshort)value;

- (void)writeNullableWithJavaUtilDate:(JavaUtilDate *)value;

- (void)writeNullableWithJavaLangLong:(JavaLangLong *)value;

- (void)writeStringWithNSString:(NSString *)value;

- (void)writeUIntWithInt:(jint)value;

- (void)writeUInt16WithInt:(jint)value;

- (void)writeUInt16sWithIntArray:(IOSIntArray *)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverProtocolsBinaryWriter)

FOUNDATION_EXPORT void ComUsOpenserverProtocolsBinaryWriter_init(ComUsOpenserverProtocolsBinaryWriter *self);

FOUNDATION_EXPORT ComUsOpenserverProtocolsBinaryWriter *new_ComUsOpenserverProtocolsBinaryWriter_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComUsOpenserverProtocolsBinaryWriter *create_ComUsOpenserverProtocolsBinaryWriter_init();

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverProtocolsBinaryWriter)

#endif

#pragma pop_macro("BinaryWriter_INCLUDE_ALL")
