//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/hello/HelloProtocolClient.java
//

#include "J2ObjC_header.h"

#pragma push_macro("HelloProtocolClient_INCLUDE_ALL")
#ifdef HelloProtocolClient_RESTRICT
#define HelloProtocolClient_INCLUDE_ALL 0
#else
#define HelloProtocolClient_INCLUDE_ALL 1
#endif
#undef HelloProtocolClient_RESTRICT

#if !defined (ComUsOpenserverProtocolsHelloHelloProtocolClient_) && (HelloProtocolClient_INCLUDE_ALL || defined(ComUsOpenserverProtocolsHelloHelloProtocolClient_INCLUDE))
#define ComUsOpenserverProtocolsHelloHelloProtocolClient_

#define HelloProtocol_RESTRICT 1
#define ComUsOpenserverProtocolsHelloHelloProtocol_INCLUDE 1
#include "HelloProtocol.h"

@class ComUsOpenserverProtocolsBinaryReader;
@protocol ComUsOpenserverProtocolsHelloIHelloProtocolObserver;

@interface ComUsOpenserverProtocolsHelloHelloProtocolClient : ComUsOpenserverProtocolsHelloHelloProtocol

#pragma mark Public

- (instancetype)init;

- (NSString *)helloWithNSString:(NSString *)message;

- (void)helloAsyncWithNSString:(NSString *)message;

- (NSString *)helloBackgroundThreadWithNSString:(NSString *)message;

- (void)helloBackgroundThreadAsyncWithNSString:(NSString *)message;

- (void)onPacketReceivedWithComUsOpenserverProtocolsBinaryReader:(ComUsOpenserverProtocolsBinaryReader *)br;

- (void)setHelloObserverWithComUsOpenserverProtocolsHelloIHelloProtocolObserver:(id<ComUsOpenserverProtocolsHelloIHelloProtocolObserver>)callbackInterface;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverProtocolsHelloHelloProtocolClient)

FOUNDATION_EXPORT void ComUsOpenserverProtocolsHelloHelloProtocolClient_init(ComUsOpenserverProtocolsHelloHelloProtocolClient *self);

FOUNDATION_EXPORT ComUsOpenserverProtocolsHelloHelloProtocolClient *new_ComUsOpenserverProtocolsHelloHelloProtocolClient_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComUsOpenserverProtocolsHelloHelloProtocolClient *create_ComUsOpenserverProtocolsHelloHelloProtocolClient_init();

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverProtocolsHelloHelloProtocolClient)

#endif

#pragma pop_macro("HelloProtocolClient_INCLUDE_ALL")
