//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/hello/HelloProtocolClient.java
//

#ifndef _ComUsOpenserverProtocolsHelloHelloProtocolClient_H_
#define _ComUsOpenserverProtocolsHelloHelloProtocolClient_H_

#include "HelloProtocol.h"
#include "J2ObjC_header.h"

@class ComUsOpenserverProtocolsBinaryReader;
@protocol ComUsOpenserverProtocolsHelloIHelloProtocolObserver;

@interface ComUsOpenserverProtocolsHelloHelloProtocolClient : ComUsOpenserverProtocolsHelloHelloProtocol

#pragma mark Public

- (instancetype)init;

- (NSString *)helloWithNSString:(NSString *)message;

- (void)helloAsyncWithNSString:(NSString *)message;

- (NSString *)helloBackgroundThreadWithNSString:(NSString *)message;

- (void)helloBackgroundThreadAsyncWithNSString:(NSString *)message;

- (void)onPacketReceivedWithComUsOpenserverProtocolsBinaryReader:(ComUsOpenserverProtocolsBinaryReader *)br;

- (void)setHelloObserverWithComUsOpenserverProtocolsHelloIHelloProtocolObserver:(id<ComUsOpenserverProtocolsHelloIHelloProtocolObserver>)callbackInterface;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverProtocolsHelloHelloProtocolClient)

FOUNDATION_EXPORT void ComUsOpenserverProtocolsHelloHelloProtocolClient_init(ComUsOpenserverProtocolsHelloHelloProtocolClient *self);

FOUNDATION_EXPORT ComUsOpenserverProtocolsHelloHelloProtocolClient *new_ComUsOpenserverProtocolsHelloHelloProtocolClient_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverProtocolsHelloHelloProtocolClient)

#endif // _ComUsOpenserverProtocolsHelloHelloProtocolClient_H_
