//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/Logger.java
//

#ifndef _ComUsOpenserverLogger_H_
#define _ComUsOpenserverLogger_H_

#include "J2ObjC_header.h"

@class ComUsOpenserverLevelEnum;
@class JavaLangException;
@protocol ComUsOpenserverILoggerObserver;

@interface ComUsOpenserverLogger : NSObject {
 @public
  jboolean logDebug_;
  jboolean logPackets_;
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithComUsOpenserverILoggerObserver:(id<ComUsOpenserverILoggerObserver>)callback;

- (jboolean)getLogDebug;

- (jboolean)getLogPackets;

- (void)logWithJavaLangException:(JavaLangException *)ex;

- (void)logWithComUsOpenserverLevelEnum:(ComUsOpenserverLevelEnum *)level
                           withNSString:(NSString *)message;

- (void)setILoggerObserverWithComUsOpenserverILoggerObserver:(id<ComUsOpenserverILoggerObserver>)callback;

- (void)setLogDebugWithBoolean:(jboolean)logDebug;

- (void)setLogPacketsWithBoolean:(jboolean)logPackets;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverLogger)

FOUNDATION_EXPORT void ComUsOpenserverLogger_init(ComUsOpenserverLogger *self);

FOUNDATION_EXPORT ComUsOpenserverLogger *new_ComUsOpenserverLogger_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComUsOpenserverLogger_initWithComUsOpenserverILoggerObserver_(ComUsOpenserverLogger *self, id<ComUsOpenserverILoggerObserver> callback);

FOUNDATION_EXPORT ComUsOpenserverLogger *new_ComUsOpenserverLogger_initWithComUsOpenserverILoggerObserver_(id<ComUsOpenserverILoggerObserver> callback) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverLogger)

#endif // _ComUsOpenserverLogger_H_
