//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/ProtocolConfiguration.java
//

#ifndef _ComUsOpenserverProtocolsProtocolConfiguration_H_
#define _ComUsOpenserverProtocolsProtocolConfiguration_H_

#include "J2ObjC_header.h"

@interface ComUsOpenserverProtocolsProtocolConfiguration : NSObject

#pragma mark Public

- (instancetype)initWithInt:(jint)id_
               withNSString:(NSString *)classPath;

- (NSString *)getClassPath;

- (jint)getId;

- (void)setClassPathWithNSString:(NSString *)classPath;

- (void)setIdWithInt:(jint)id_;

#pragma mark Protected

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverProtocolsProtocolConfiguration)

FOUNDATION_EXPORT void ComUsOpenserverProtocolsProtocolConfiguration_init(ComUsOpenserverProtocolsProtocolConfiguration *self);

FOUNDATION_EXPORT ComUsOpenserverProtocolsProtocolConfiguration *new_ComUsOpenserverProtocolsProtocolConfiguration_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComUsOpenserverProtocolsProtocolConfiguration_initWithInt_withNSString_(ComUsOpenserverProtocolsProtocolConfiguration *self, jint id_, NSString *classPath);

FOUNDATION_EXPORT ComUsOpenserverProtocolsProtocolConfiguration *new_ComUsOpenserverProtocolsProtocolConfiguration_initWithInt_withNSString_(jint id_, NSString *classPath) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverProtocolsProtocolConfiguration)

#endif // _ComUsOpenserverProtocolsProtocolConfiguration_H_
