//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/ProtocolBase.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ProtocolBase_INCLUDE_ALL")
#ifdef ProtocolBase_RESTRICT
#define ProtocolBase_INCLUDE_ALL 0
#else
#define ProtocolBase_INCLUDE_ALL 1
#endif
#undef ProtocolBase_RESTRICT

#if !defined (ComUsOpenserverProtocolsProtocolBase_) && (ProtocolBase_INCLUDE_ALL || defined(ComUsOpenserverProtocolsProtocolBase_INCLUDE))
#define ComUsOpenserverProtocolsProtocolBase_

@class ComUsOpenserverLevel;
@class ComUsOpenserverProtocolsBinaryReader;
@class ComUsOpenserverProtocolsProtocolConfiguration;
@class ComUsOpenserverSessionSession;

@interface ComUsOpenserverProtocolsProtocolBase : NSObject {
 @public
  ComUsOpenserverSessionSession *session_;
}

#pragma mark Public

- (instancetype)init;

- (void)close;

- (void)dispose;

- (void)initialize__WithComUsOpenserverSessionSession:(ComUsOpenserverSessionSession *)session
    withComUsOpenserverProtocolsProtocolConfiguration:(ComUsOpenserverProtocolsProtocolConfiguration *)pc
                                               withId:(id)userData OBJC_METHOD_FAMILY_NONE;

- (void)onErrorReceivedWithNSString:(NSString *)message;

- (void)onPacketReceivedWithComUsOpenserverProtocolsBinaryReader:(ComUsOpenserverProtocolsBinaryReader *)br;

#pragma mark Protected

- (void)logWithComUsOpenserverLevel:(ComUsOpenserverLevel *)level
                       withNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverProtocolsProtocolBase)

J2OBJC_FIELD_SETTER(ComUsOpenserverProtocolsProtocolBase, session_, ComUsOpenserverSessionSession *)

FOUNDATION_EXPORT void ComUsOpenserverProtocolsProtocolBase_init(ComUsOpenserverProtocolsProtocolBase *self);

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverProtocolsProtocolBase)

#endif

#pragma pop_macro("ProtocolBase_INCLUDE_ALL")
