//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/configuration/ServerConfiguration.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ServerConfiguration_INCLUDE_ALL")
#ifdef ServerConfiguration_RESTRICT
#define ServerConfiguration_INCLUDE_ALL 0
#else
#define ServerConfiguration_INCLUDE_ALL 1
#endif
#undef ServerConfiguration_RESTRICT

#if !defined (ComUsOpenserverConfigurationServerConfiguration_) && (ServerConfiguration_INCLUDE_ALL || defined(ComUsOpenserverConfigurationServerConfiguration_INCLUDE))
#define ComUsOpenserverConfigurationServerConfiguration_

@class ComUsOpenserverConfigurationTlsConfiguration;

@interface ComUsOpenserverConfigurationServerConfiguration : NSObject

#pragma mark Public

- (instancetype)init;

- (NSString *)getHost;

- (jint)getIdleTimeout;

- (jint)getIdleTimeoutInTicks;

- (jint)getPort;

- (jint)getSocketTimeout;

- (jint)getSocketTimeoutInTicks;

- (ComUsOpenserverConfigurationTlsConfiguration *)getTlsConfiguration;

- (void)setHostWithNSString:(NSString *)value;

- (void)setIdleTimeoutWithInt:(jint)value;

- (void)setPortWithInt:(jint)value;

- (void)setSocketTimeoutWithInt:(jint)value;

- (void)setTlsConfigurationWithComUsOpenserverConfigurationTlsConfiguration:(ComUsOpenserverConfigurationTlsConfiguration *)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverConfigurationServerConfiguration)

FOUNDATION_EXPORT void ComUsOpenserverConfigurationServerConfiguration_init(ComUsOpenserverConfigurationServerConfiguration *self);

FOUNDATION_EXPORT ComUsOpenserverConfigurationServerConfiguration *new_ComUsOpenserverConfigurationServerConfiguration_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComUsOpenserverConfigurationServerConfiguration *create_ComUsOpenserverConfigurationServerConfiguration_init();

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverConfigurationServerConfiguration)

#endif

#pragma pop_macro("ServerConfiguration_INCLUDE_ALL")
