//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/session/SessionInitializer.java
//

#include "Client.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "ProtocolBase.h"
#include "ServerConfiguration.h"
#include "Session.h"
#include "SessionInitializer.h"
#include "java/lang/Exception.h"
#include "java/lang/Thread.h"

@interface ComUsOpenserverSessionSessionInitializer () {
 @public
  ComUsOpenserverClient *client_;
  jint protocolId_;
  ComUsOpenserverProtocolsProtocolBase *p_;
  JavaLangException *exception_;
}

@end

J2OBJC_FIELD_SETTER(ComUsOpenserverSessionSessionInitializer, client_, ComUsOpenserverClient *)
J2OBJC_FIELD_SETTER(ComUsOpenserverSessionSessionInitializer, p_, ComUsOpenserverProtocolsProtocolBase *)
J2OBJC_FIELD_SETTER(ComUsOpenserverSessionSessionInitializer, exception_, JavaLangException *)

inline jint ComUsOpenserverSessionSessionInitializer_get_id();
inline jint ComUsOpenserverSessionSessionInitializer_set_id(jint value);
inline jint *ComUsOpenserverSessionSessionInitializer_getRef_id();
static jint ComUsOpenserverSessionSessionInitializer_id;
J2OBJC_STATIC_FIELD_PRIMITIVE(ComUsOpenserverSessionSessionInitializer, id, jint)

@implementation ComUsOpenserverSessionSessionInitializer

- (instancetype)initWithComUsOpenserverClient:(ComUsOpenserverClient *)client
                                      withInt:(jint)protocolId {
  ComUsOpenserverSessionSessionInitializer_initWithComUsOpenserverClient_withInt_(self, client, protocolId);
  return self;
}

- (ComUsOpenserverProtocolsProtocolBase *)initializeAsync {
  @synchronized(self) {
    JavaLangThread *t = new_JavaLangThread_initWithJavaLangRunnable_withNSString_(self, JreStrcat("$I", @"SessionInitializer", ++ComUsOpenserverSessionSessionInitializer_id));
    [t start];
    [self waitWithLong:[((ComUsOpenserverConfigurationServerConfiguration *) nil_chk([((ComUsOpenserverClient *) nil_chk(client_)) getServerConfiguration])) getSocketTimeoutInTicks]];
  }
  if (exception_ != nil) @throw exception_;
  return p_;
}

- (void)run {
  @synchronized(self) {
    @try {
      (void) [self initialize__WithInt:protocolId_];
    }
    @catch (JavaLangException *ex) {
      exception_ = ex;
    }
    [self notifyAll];
  }
}

- (ComUsOpenserverProtocolsProtocolBase *)initialize__WithInt:(jint)protocolId {
  p_ = [((ComUsOpenserverSessionSession *) nil_chk([((ComUsOpenserverClient *) nil_chk(client_)) getSession])) initialize__WithInt:protocolId withId:[client_ getUserData]];
  return p_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComUsOpenserverClient:withInt:", "SessionInitializer", NULL, 0x1, NULL, NULL },
    { "initializeAsync", NULL, "Lcom.us.openserver.protocols.ProtocolBase;", 0x1, "Ljava.lang.Exception;", NULL },
    { "run", NULL, "V", 0x1, NULL, NULL },
    { "initialize__WithInt:", "initialize", "Lcom.us.openserver.protocols.ProtocolBase;", 0x1, "Ljava.lang.Exception;", NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "client_", NULL, 0x2, "Lcom.us.openserver.Client;", NULL, NULL, .constantValue.asLong = 0 },
    { "protocolId_", NULL, 0x2, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "p_", NULL, 0x2, "Lcom.us.openserver.protocols.ProtocolBase;", NULL, NULL, .constantValue.asLong = 0 },
    { "exception_", NULL, 0x2, "Ljava.lang.Exception;", NULL, NULL, .constantValue.asLong = 0 },
    { "id", "id", 0xa, "I", &ComUsOpenserverSessionSessionInitializer_id, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ComUsOpenserverSessionSessionInitializer = { 2, "SessionInitializer", "com.us.openserver.session", NULL, 0x1, 4, methods, 5, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComUsOpenserverSessionSessionInitializer;
}

@end

void ComUsOpenserverSessionSessionInitializer_initWithComUsOpenserverClient_withInt_(ComUsOpenserverSessionSessionInitializer *self, ComUsOpenserverClient *client, jint protocolId) {
  NSObject_init(self);
  self->client_ = client;
  self->protocolId_ = protocolId;
}

ComUsOpenserverSessionSessionInitializer *new_ComUsOpenserverSessionSessionInitializer_initWithComUsOpenserverClient_withInt_(ComUsOpenserverClient *client, jint protocolId) {
  ComUsOpenserverSessionSessionInitializer *self = [ComUsOpenserverSessionSessionInitializer alloc];
  ComUsOpenserverSessionSessionInitializer_initWithComUsOpenserverClient_withInt_(self, client, protocolId);
  return self;
}

ComUsOpenserverSessionSessionInitializer *create_ComUsOpenserverSessionSessionInitializer_initWithComUsOpenserverClient_withInt_(ComUsOpenserverClient *client, jint protocolId) {
  return new_ComUsOpenserverSessionSessionInitializer_initWithComUsOpenserverClient_withInt_(client, protocolId);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComUsOpenserverSessionSessionInitializer)
