//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/winauth/WinAuthProtocol.java
//

#ifndef _ComUsOpenserverProtocolsWinauthWinAuthProtocol_H_
#define _ComUsOpenserverProtocolsWinauthWinAuthProtocol_H_

#include "AuthenticationProtocolBase.h"
#include "J2ObjC_header.h"

@class ComUsOpenserverLevelEnum;

#define ComUsOpenserverProtocolsWinauthWinAuthProtocol_PROTOCOL_IDENTIFIER 2

@interface ComUsOpenserverProtocolsWinauthWinAuthProtocol : ComUsOpenserverProtocolsAuthenticationProtocolBase

#pragma mark Protected

- (instancetype)init;

- (void)logWithComUsOpenserverLevelEnum:(ComUsOpenserverLevelEnum *)level
                           withNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverProtocolsWinauthWinAuthProtocol)

J2OBJC_STATIC_FIELD_GETTER(ComUsOpenserverProtocolsWinauthWinAuthProtocol, PROTOCOL_IDENTIFIER, jint)

FOUNDATION_EXPORT void ComUsOpenserverProtocolsWinauthWinAuthProtocol_init(ComUsOpenserverProtocolsWinauthWinAuthProtocol *self);

FOUNDATION_EXPORT ComUsOpenserverProtocolsWinauthWinAuthProtocol *new_ComUsOpenserverProtocolsWinauthWinAuthProtocol_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverProtocolsWinauthWinAuthProtocol)

#endif // _ComUsOpenserverProtocolsWinauthWinAuthProtocol_H_
