//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/databaseauth/DatabaseAuthProtocolCommands.java
//

#include "DatabaseAuthProtocolCommands.h"
#include "J2ObjC_source.h"

@implementation ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "AUTHENTICATE", "AUTHENTICATE", 0x19, "I", NULL, NULL, .constantValue.asInt = ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands_AUTHENTICATE },
    { "AUTHENTICATED", "AUTHENTICATED", 0x19, "I", NULL, NULL, .constantValue.asInt = ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands_AUTHENTICATED },
    { "ACCESS_DENIED", "ACCESS_DENIED", 0x19, "I", NULL, NULL, .constantValue.asInt = ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands_ACCESS_DENIED },
    { "ERROR", "ERROR", 0x19, "I", NULL, NULL, .constantValue.asInt = ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands_ERROR },
  };
  static const J2ObjcClassInfo _ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands = { 2, "DatabaseAuthProtocolCommands", "com.us.openserver.protocols.databaseauth", NULL, 0x1, 1, methods, 4, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands;
}

@end

void ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands_init(ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands *self) {
  NSObject_init(self);
}

ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands *new_ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands_init() {
  ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands *self = [ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands alloc];
  ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands_init(self);
  return self;
}

ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands *create_ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands_init() {
  return new_ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands_init();
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocolCommands)
