//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/databaseauth/DatabaseAuthProtocol.java
//

#include "J2ObjC_header.h"

#pragma push_macro("DatabaseAuthProtocol_INCLUDE_ALL")
#ifdef DatabaseAuthProtocol_RESTRICT
#define DatabaseAuthProtocol_INCLUDE_ALL 0
#else
#define DatabaseAuthProtocol_INCLUDE_ALL 1
#endif
#undef DatabaseAuthProtocol_RESTRICT

#if !defined (ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol_) && (DatabaseAuthProtocol_INCLUDE_ALL || defined(ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol_INCLUDE))
#define ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol_

#define AuthenticationProtocolBase_RESTRICT 1
#define ComUsOpenserverProtocolsAuthenticationProtocolBase_INCLUDE 1
#include "AuthenticationProtocolBase.h"

@class ComUsOpenserverLevel;

@interface ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol : ComUsOpenserverProtocolsAuthenticationProtocolBase

#pragma mark Protected

- (instancetype)init;

- (void)logWithComUsOpenserverLevel:(ComUsOpenserverLevel *)level
                       withNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol)

inline jint ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol_get_PROTOCOL_IDENTIFIER();
#define ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol_PROTOCOL_IDENTIFIER 3
J2OBJC_STATIC_FIELD_CONSTANT(ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol, PROTOCOL_IDENTIFIER, jint)

FOUNDATION_EXPORT void ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol_init(ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol *self);

FOUNDATION_EXPORT ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol *new_ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol *create_ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol_init();

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverProtocolsDatabaseauthDatabaseAuthProtocol)

#endif

#pragma pop_macro("DatabaseAuthProtocol_INCLUDE_ALL")
