//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/configuration/TlsConfiguration.java
//


#include "J2ObjC_source.h"
#include "com/us/openserver/configuration/TlsConfiguration.h"

@interface ComUsOpenserverConfigurationTlsConfiguration () {
 @public
  jboolean enabled_;
  NSString *certificate_;
  jboolean requireRemoteCertificate_;
  jboolean allowSelfSignedCertificate_;
  jboolean checkCertificateRevocation_;
  jboolean allowCertificateChainErrors_;
}

@end

J2OBJC_FIELD_SETTER(ComUsOpenserverConfigurationTlsConfiguration, certificate_, NSString *)

@implementation ComUsOpenserverConfigurationTlsConfiguration

- (jboolean)getAllowCertificateChainErrors {
  return allowCertificateChainErrors_;
}

- (void)setAllowCertificateChainErrorsWithBoolean:(jboolean)value {
  allowCertificateChainErrors_ = value;
}

- (jboolean)getCheckCertificateRevocation {
  return checkCertificateRevocation_;
}

- (void)setCheckCertificateRevocationWithBoolean:(jboolean)value {
  checkCertificateRevocation_ = value;
}

- (jboolean)getAllowSelfSignedCertificate {
  return allowSelfSignedCertificate_;
}

- (void)setAllowSelfSignedCertificateWithBoolean:(jboolean)value {
  allowSelfSignedCertificate_ = value;
}

- (jboolean)getRequireRemoteCertificate {
  return requireRemoteCertificate_;
}

- (void)setRequireRemoteCertificateWithBoolean:(jboolean)value {
  requireRemoteCertificate_ = value;
}

- (NSString *)getCertificate {
  return certificate_;
}

- (void)setCertificateWithNSString:(NSString *)value {
  certificate_ = value;
}

- (jboolean)isEnabled {
  return enabled_;
}

- (void)setEnabledWithBoolean:(jboolean)value {
  enabled_ = value;
}

- (instancetype)init {
  ComUsOpenserverConfigurationTlsConfiguration_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getAllowCertificateChainErrors", NULL, "Z", 0x1, NULL, NULL },
    { "setAllowCertificateChainErrorsWithBoolean:", "setAllowCertificateChainErrors", "V", 0x1, NULL, NULL },
    { "getCheckCertificateRevocation", NULL, "Z", 0x1, NULL, NULL },
    { "setCheckCertificateRevocationWithBoolean:", "setCheckCertificateRevocation", "V", 0x1, NULL, NULL },
    { "getAllowSelfSignedCertificate", NULL, "Z", 0x1, NULL, NULL },
    { "setAllowSelfSignedCertificateWithBoolean:", "setAllowSelfSignedCertificate", "V", 0x1, NULL, NULL },
    { "getRequireRemoteCertificate", NULL, "Z", 0x1, NULL, NULL },
    { "setRequireRemoteCertificateWithBoolean:", "setRequireRemoteCertificate", "V", 0x1, NULL, NULL },
    { "getCertificate", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "setCertificateWithNSString:", "setCertificate", "V", 0x1, NULL, NULL },
    { "isEnabled", NULL, "Z", 0x1, NULL, NULL },
    { "setEnabledWithBoolean:", "setEnabled", "V", 0x1, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "enabled_", NULL, 0x2, "Z", NULL, NULL,  },
    { "certificate_", NULL, 0x2, "Ljava.lang.String;", NULL, NULL,  },
    { "requireRemoteCertificate_", NULL, 0x2, "Z", NULL, NULL,  },
    { "allowSelfSignedCertificate_", NULL, 0x2, "Z", NULL, NULL,  },
    { "checkCertificateRevocation_", NULL, 0x2, "Z", NULL, NULL,  },
    { "allowCertificateChainErrors_", NULL, 0x2, "Z", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _ComUsOpenserverConfigurationTlsConfiguration = { 2, "TlsConfiguration", "com.us.openserver.configuration", NULL, 0x1, 13, methods, 6, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComUsOpenserverConfigurationTlsConfiguration;
}

@end

void ComUsOpenserverConfigurationTlsConfiguration_init(ComUsOpenserverConfigurationTlsConfiguration *self) {
  (void) NSObject_init(self);
}

ComUsOpenserverConfigurationTlsConfiguration *new_ComUsOpenserverConfigurationTlsConfiguration_init() {
  ComUsOpenserverConfigurationTlsConfiguration *self = [ComUsOpenserverConfigurationTlsConfiguration alloc];
  ComUsOpenserverConfigurationTlsConfiguration_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComUsOpenserverConfigurationTlsConfiguration)
