//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/BinaryReader.java
//

#include "J2ObjC_header.h"

#pragma push_macro("BinaryReader_INCLUDE_ALL")
#ifdef BinaryReader_RESTRICT
#define BinaryReader_INCLUDE_ALL 0
#else
#define BinaryReader_INCLUDE_ALL 1
#endif
#undef BinaryReader_RESTRICT

#if !defined (ComUsOpenserverProtocolsBinaryReader_) && (BinaryReader_INCLUDE_ALL || defined(ComUsOpenserverProtocolsBinaryReader_INCLUDE))
#define ComUsOpenserverProtocolsBinaryReader_

#define JavaIoByteArrayInputStream_RESTRICT 1
#define JavaIoByteArrayInputStream_INCLUDE 1
#include "java/io/ByteArrayInputStream.h"

@class IOSByteArray;
@class IOSIntArray;
@class JavaLangLong;
@class JavaMathBigDecimal;
@class JavaUtilDate;

@interface ComUsOpenserverProtocolsBinaryReader : JavaIoByteArrayInputStream

#pragma mark Public

- (instancetype)initWithByteArray:(IOSByteArray *)buf;

- (jboolean)readBoolean;

- (jbyte)readByte;

- (IOSByteArray *)readBytes;

- (JavaUtilDate *)readDateTime;

- (JavaMathBigDecimal *)readDecimal;

- (jshort)readInt16;

- (jint)readInt32;

- (IOSIntArray *)readInt32s;

- (jlong)readLong;

- (JavaUtilDate *)readNullableDateTime;

- (JavaLangLong *)readNullableTimeSpan;

- (NSString *)readString;

- (jint)readUInt16;

- (IOSIntArray *)readUInt16s;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverProtocolsBinaryReader)

FOUNDATION_EXPORT void ComUsOpenserverProtocolsBinaryReader_initWithByteArray_(ComUsOpenserverProtocolsBinaryReader *self, IOSByteArray *buf);

FOUNDATION_EXPORT ComUsOpenserverProtocolsBinaryReader *new_ComUsOpenserverProtocolsBinaryReader_initWithByteArray_(IOSByteArray *buf) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComUsOpenserverProtocolsBinaryReader *create_ComUsOpenserverProtocolsBinaryReader_initWithByteArray_(IOSByteArray *buf);

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverProtocolsBinaryReader)

#endif

#pragma pop_macro("BinaryReader_INCLUDE_ALL")
