//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/IClientObserver.java
//

#ifndef _ComUsOpenserverIClientObserver_H_
#define _ComUsOpenserverIClientObserver_H_

#include "J2ObjC_header.h"

@class JavaLangException;

@protocol ComUsOpenserverIClientObserver < NSObject, JavaObject >

- (void)onConnectionLostWithJavaLangException:(JavaLangException *)ex;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverIClientObserver)

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverIClientObserver)

#endif // _ComUsOpenserverIClientObserver_H_
