//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/ILoggerObserver.java
//

#ifndef _ComUsOpenserverILoggerObserver_H_
#define _ComUsOpenserverILoggerObserver_H_

#include "J2ObjC_header.h"

@class ComUsOpenserverLevelEnum;

@protocol ComUsOpenserverILoggerObserver < NSObject, JavaObject >

- (void)onLogMessageWithComUsOpenserverLevelEnum:(ComUsOpenserverLevelEnum *)level
                                    withNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverILoggerObserver)

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverILoggerObserver)

#endif // _ComUsOpenserverILoggerObserver_H_
