//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/keepalive/KeepAliveProtocol.java
//

#ifndef _ComUsOpenserverProtocolsKeepaliveKeepAliveProtocol_H_
#define _ComUsOpenserverProtocolsKeepaliveKeepAliveProtocol_H_

#include "J2ObjC_header.h"
#include "ProtocolBase.h"
#include "java/lang/Runnable.h"

@class ComUsOpenserverLevelEnum;
@class ComUsOpenserverProtocolsBinaryReader;
@class ComUsOpenserverProtocolsProtocolConfiguration;
@class ComUsOpenserverSessionSession;

#define ComUsOpenserverProtocolsKeepaliveKeepAliveProtocol_PROTOCOL_IDENTIFIER 1
#define ComUsOpenserverProtocolsKeepaliveKeepAliveProtocol_INTERVAL 10000

@interface ComUsOpenserverProtocolsKeepaliveKeepAliveProtocol : ComUsOpenserverProtocolsProtocolBase < JavaLangRunnable >

#pragma mark Public

- (instancetype)init;

- (void)close;

- (void)dispose;

- (void)initialize__WithComUsOpenserverSessionSession:(ComUsOpenserverSessionSession *)session
    withComUsOpenserverProtocolsProtocolConfiguration:(ComUsOpenserverProtocolsProtocolConfiguration *)pc
                                               withId:(id)userData OBJC_METHOD_FAMILY_NONE;

- (void)onPacketReceivedWithComUsOpenserverProtocolsBinaryReader:(ComUsOpenserverProtocolsBinaryReader *)br;

- (void)run;

#pragma mark Protected

- (void)logWithComUsOpenserverLevelEnum:(ComUsOpenserverLevelEnum *)level
                           withNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverProtocolsKeepaliveKeepAliveProtocol)

J2OBJC_STATIC_FIELD_GETTER(ComUsOpenserverProtocolsKeepaliveKeepAliveProtocol, PROTOCOL_IDENTIFIER, jint)

J2OBJC_STATIC_FIELD_GETTER(ComUsOpenserverProtocolsKeepaliveKeepAliveProtocol, INTERVAL, jint)

FOUNDATION_EXPORT void ComUsOpenserverProtocolsKeepaliveKeepAliveProtocol_init(ComUsOpenserverProtocolsKeepaliveKeepAliveProtocol *self);

FOUNDATION_EXPORT ComUsOpenserverProtocolsKeepaliveKeepAliveProtocol *new_ComUsOpenserverProtocolsKeepaliveKeepAliveProtocol_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverProtocolsKeepaliveKeepAliveProtocol)

#endif // _ComUsOpenserverProtocolsKeepaliveKeepAliveProtocol_H_
