//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/session/PacketHandler.java
//

#include "J2ObjC_header.h"

#pragma push_macro("PacketHandler_INCLUDE_ALL")
#ifdef PacketHandler_RESTRICT
#define PacketHandler_INCLUDE_ALL 0
#else
#define PacketHandler_INCLUDE_ALL 1
#endif
#undef PacketHandler_RESTRICT

#if !defined (ComUsOpenserverSessionPacketHandler_) && (PacketHandler_INCLUDE_ALL || defined(ComUsOpenserverSessionPacketHandler_INCLUDE))
#define ComUsOpenserverSessionPacketHandler_

#define JavaLangRunnable_RESTRICT 1
#define JavaLangRunnable_INCLUDE 1
#include "java/lang/Runnable.h"

@class ComUsOpenserverProtocolsBinaryReader;
@class ComUsOpenserverSessionSession;
@class JavaLangException;

@interface ComUsOpenserverSessionPacketHandler : NSObject < JavaLangRunnable >

#pragma mark Public

- (instancetype)initWithComUsOpenserverSessionSession:(ComUsOpenserverSessionSession *)session
             withComUsOpenserverProtocolsBinaryReader:(ComUsOpenserverProtocolsBinaryReader *)br;

- (void)execute;

- (JavaLangException *)getException;

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverSessionPacketHandler)

FOUNDATION_EXPORT void ComUsOpenserverSessionPacketHandler_initWithComUsOpenserverSessionSession_withComUsOpenserverProtocolsBinaryReader_(ComUsOpenserverSessionPacketHandler *self, ComUsOpenserverSessionSession *session, ComUsOpenserverProtocolsBinaryReader *br);

FOUNDATION_EXPORT ComUsOpenserverSessionPacketHandler *new_ComUsOpenserverSessionPacketHandler_initWithComUsOpenserverSessionSession_withComUsOpenserverProtocolsBinaryReader_(ComUsOpenserverSessionSession *session, ComUsOpenserverProtocolsBinaryReader *br) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComUsOpenserverSessionPacketHandler *create_ComUsOpenserverSessionPacketHandler_initWithComUsOpenserverSessionSession_withComUsOpenserverProtocolsBinaryReader_(ComUsOpenserverSessionSession *session, ComUsOpenserverProtocolsBinaryReader *br);

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverSessionPacketHandler)

#endif

#pragma pop_macro("PacketHandler_INCLUDE_ALL")
