//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/session/SessionOpener.java
//

#ifndef _ComUsOpenserverSessionSessionOpener_H_
#define _ComUsOpenserverSessionSessionOpener_H_

#include "J2ObjC_header.h"
#include "java/lang/Runnable.h"

@class ComUsOpenserverClient;
@class ComUsOpenserverSessionSession;

@interface ComUsOpenserverSessionSessionOpener : NSObject < JavaLangRunnable >

#pragma mark Public

- (instancetype)initWithComUsOpenserverClient:(ComUsOpenserverClient *)client;

- (ComUsOpenserverSessionSession *)connect;

- (ComUsOpenserverSessionSession *)connectBackgroundThread;

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverSessionSessionOpener)

FOUNDATION_EXPORT void ComUsOpenserverSessionSessionOpener_initWithComUsOpenserverClient_(ComUsOpenserverSessionSessionOpener *self, ComUsOpenserverClient *client);

FOUNDATION_EXPORT ComUsOpenserverSessionSessionOpener *new_ComUsOpenserverSessionSessionOpener_initWithComUsOpenserverClient_(ComUsOpenserverClient *client) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverSessionSessionOpener)

#endif // _ComUsOpenserverSessionSessionOpener_H_
