//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/configuration/TlsConfiguration.java
//

#ifndef _ComUsOpenserverConfigurationTlsConfiguration_H_
#define _ComUsOpenserverConfigurationTlsConfiguration_H_

#include "J2ObjC_header.h"

@interface ComUsOpenserverConfigurationTlsConfiguration : NSObject

#pragma mark Public

- (instancetype)init;

- (jboolean)getAllowCertificateChainErrors;

- (jboolean)getAllowSelfSignedCertificate;

- (NSString *)getCertificate;

- (jboolean)getCheckCertificateRevocation;

- (jboolean)getRequireRemoteCertificate;

- (jboolean)isEnabled;

- (void)setAllowCertificateChainErrorsWithBoolean:(jboolean)value;

- (void)setAllowSelfSignedCertificateWithBoolean:(jboolean)value;

- (void)setCertificateWithNSString:(NSString *)value;

- (void)setCheckCertificateRevocationWithBoolean:(jboolean)value;

- (void)setEnabledWithBoolean:(jboolean)value;

- (void)setRequireRemoteCertificateWithBoolean:(jboolean)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverConfigurationTlsConfiguration)

FOUNDATION_EXPORT void ComUsOpenserverConfigurationTlsConfiguration_init(ComUsOpenserverConfigurationTlsConfiguration *self);

FOUNDATION_EXPORT ComUsOpenserverConfigurationTlsConfiguration *new_ComUsOpenserverConfigurationTlsConfiguration_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverConfigurationTlsConfiguration)

#endif // _ComUsOpenserverConfigurationTlsConfiguration_H_
