//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/Client.java
//

#ifndef _ComUsOpenserverClient_H_
#define _ComUsOpenserverClient_H_

#include "J2ObjC_header.h"

@class ComUsOpenserverConfigurationServerConfiguration;
@class ComUsOpenserverLogger;
@class ComUsOpenserverProtocolsProtocolBase;
@class ComUsOpenserverSessionSession;
@class IOSIntArray;
@class JavaLangException;
@class JavaUtilHashMap;
@protocol ComUsOpenserverIClientObserver;

@interface ComUsOpenserverClient : NSObject

#pragma mark Public

- (instancetype)initWithComUsOpenserverIClientObserver:(id<ComUsOpenserverIClientObserver>)clientObserver
   withComUsOpenserverConfigurationServerConfiguration:(ComUsOpenserverConfigurationServerConfiguration *)serverConfiguration
                                   withJavaUtilHashMap:(JavaUtilHashMap *)protocolConfigurations
                             withComUsOpenserverLogger:(ComUsOpenserverLogger *)logger
                                                withId:(id)userData;

- (void)close;

- (void)closeWithInt:(jint)protocolId;

- (void)closeAsync;

- (void)closeAsyncWithInt:(jint)protocolId;

- (void)connect;

- (void)connectAsync;

- (ComUsOpenserverLogger *)getLogger;

- (JavaUtilHashMap *)getProtocolConfigurations;

- (ComUsOpenserverConfigurationServerConfiguration *)getServerConfiguration;

- (IOSIntArray *)getServerSupportedProtocolIds;

- (ComUsOpenserverSessionSession *)getSession;

- (id)getUserData;

- (ComUsOpenserverProtocolsProtocolBase *)initialize__WithInt:(jint)protocolId OBJC_METHOD_FAMILY_NONE;

- (ComUsOpenserverProtocolsProtocolBase *)initializeAsyncWithInt:(jint)protocolId OBJC_METHOD_FAMILY_NONE;

- (void)onConnectionLostWithJavaLangException:(JavaLangException *)ex;

@end

J2OBJC_EMPTY_STATIC_INIT(ComUsOpenserverClient)

FOUNDATION_EXPORT void ComUsOpenserverClient_initWithComUsOpenserverIClientObserver_withComUsOpenserverConfigurationServerConfiguration_withJavaUtilHashMap_withComUsOpenserverLogger_withId_(ComUsOpenserverClient *self, id<ComUsOpenserverIClientObserver> clientObserver, ComUsOpenserverConfigurationServerConfiguration *serverConfiguration, JavaUtilHashMap *protocolConfigurations, ComUsOpenserverLogger *logger, id userData);

FOUNDATION_EXPORT ComUsOpenserverClient *new_ComUsOpenserverClient_initWithComUsOpenserverIClientObserver_withComUsOpenserverConfigurationServerConfiguration_withJavaUtilHashMap_withComUsOpenserverLogger_withId_(id<ComUsOpenserverIClientObserver> clientObserver, ComUsOpenserverConfigurationServerConfiguration *serverConfiguration, JavaUtilHashMap *protocolConfigurations, ComUsOpenserverLogger *logger, id userData) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComUsOpenserverClient)

#endif // _ComUsOpenserverClient_H_
