//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/protocols/SessionLayerProtocol.java
//


#include "J2ObjC_source.h"
#include "com/us/openserver/protocols/SessionLayerProtocol.h"

@implementation ComUsOpenserverProtocolsSessionLayerProtocol

- (instancetype)init {
  ComUsOpenserverProtocolsSessionLayerProtocol_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "PROTOCAL_IDENTIFIER_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = ComUsOpenserverProtocolsSessionLayerProtocol_PROTOCAL_IDENTIFIER },
    { "PROTOCOL_IDENTIFIER_LENGTH_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = ComUsOpenserverProtocolsSessionLayerProtocol_PROTOCOL_IDENTIFIER_LENGTH },
    { "LENGTH_LENGTH_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = ComUsOpenserverProtocolsSessionLayerProtocol_LENGTH_LENGTH },
    { "HEADER_LENGTH_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = ComUsOpenserverProtocolsSessionLayerProtocol_HEADER_LENGTH },
    { "PORT_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = ComUsOpenserverProtocolsSessionLayerProtocol_PORT },
  };
  static const J2ObjcClassInfo _ComUsOpenserverProtocolsSessionLayerProtocol = { 2, "SessionLayerProtocol", "com.us.openserver.protocols", NULL, 0x1, 1, methods, 5, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComUsOpenserverProtocolsSessionLayerProtocol;
}

@end

void ComUsOpenserverProtocolsSessionLayerProtocol_init(ComUsOpenserverProtocolsSessionLayerProtocol *self) {
  (void) NSObject_init(self);
}

ComUsOpenserverProtocolsSessionLayerProtocol *new_ComUsOpenserverProtocolsSessionLayerProtocol_init() {
  ComUsOpenserverProtocolsSessionLayerProtocol *self = [ComUsOpenserverProtocolsSessionLayerProtocol alloc];
  ComUsOpenserverProtocolsSessionLayerProtocol_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComUsOpenserverProtocolsSessionLayerProtocol)
