//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./com/us/openserver/session/SessionOpener.java
//


#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/us/openserver/Client.h"
#include "com/us/openserver/Level.h"
#include "com/us/openserver/configuration/ServerConfiguration.h"
#include "com/us/openserver/configuration/TlsConfiguration.h"
#include "com/us/openserver/session/Session.h"
#include "com/us/openserver/session/SessionOpener.h"
#include "java/lang/Exception.h"
#include "java/lang/Integer.h"
#include "java/lang/Thread.h"
#include "java/net/InetAddress.h"
#include "java/net/Socket.h"
#include "java/net/SocketException.h"

@interface ComUsOpenserverSessionSessionOpener () {
 @public
  ComUsOpenserverClient *client_;
  ComUsOpenserverSessionSession *session_;
  JavaLangException *exception_;
}

- (void)setSocketOptionsWithJavaNetSocket:(JavaNetSocket *)socket;

@end

J2OBJC_FIELD_SETTER(ComUsOpenserverSessionSessionOpener, client_, ComUsOpenserverClient *)
J2OBJC_FIELD_SETTER(ComUsOpenserverSessionSessionOpener, session_, ComUsOpenserverSessionSession *)
J2OBJC_FIELD_SETTER(ComUsOpenserverSessionSessionOpener, exception_, JavaLangException *)

static jint ComUsOpenserverSessionSessionOpener_id__;
J2OBJC_STATIC_FIELD_GETTER(ComUsOpenserverSessionSessionOpener, id__, jint)
J2OBJC_STATIC_FIELD_REF_GETTER(ComUsOpenserverSessionSessionOpener, id__, jint)

__attribute__((unused)) static void ComUsOpenserverSessionSessionOpener_setSocketOptionsWithJavaNetSocket_(ComUsOpenserverSessionSessionOpener *self, JavaNetSocket *socket);

@implementation ComUsOpenserverSessionSessionOpener

- (instancetype)initWithComUsOpenserverClient:(ComUsOpenserverClient *)client {
  ComUsOpenserverSessionSessionOpener_initWithComUsOpenserverClient_(self, client);
  return self;
}

- (ComUsOpenserverSessionSession *)connectAsync {
  @synchronized(self) {
    JavaLangThread *t = new_JavaLangThread_initWithJavaLangRunnable_withNSString_(self, JreStrcat("$I", @"SessionOpenThread", ++ComUsOpenserverSessionSessionOpener_id__));
    [t start];
    [self waitWithLong:[((ComUsOpenserverConfigurationServerConfiguration *) nil_chk([((ComUsOpenserverClient *) nil_chk(client_)) getServerConfiguration])) getSocketTimeoutInTicks]];
  }
  if (exception_ != nil) @throw exception_;
  return session_;
}

- (void)run {
  @synchronized(self) {
    @try {
      (void) [self connect];
    }
    @catch (JavaLangException *ex) {
      exception_ = ex;
    }
    [self notifyAll];
  }
}

- (ComUsOpenserverSessionSession *)connect {
  [((ComUsOpenserverClient *) nil_chk(client_)) close];
  JavaNetSocket *socket;
  ComUsOpenserverConfigurationServerConfiguration *cfg = [client_ getServerConfiguration];
  ComUsOpenserverConfigurationTlsConfiguration *tls = [((ComUsOpenserverConfigurationServerConfiguration *) nil_chk(cfg)) getTlsConfiguration];
  if (![((ComUsOpenserverConfigurationTlsConfiguration *) nil_chk(tls)) isEnabled]) {
    socket = new_JavaNetSocket_initWithNSString_withInt_([cfg getHost], [cfg getPort]);
    ComUsOpenserverSessionSessionOpener_setSocketOptionsWithJavaNetSocket_(self, socket);
  }
  else {
    @throw new_JavaLangException_initWithNSString_(@"Not implemented yet.");
  }
  session_ = new_ComUsOpenserverSessionSession_initWithComUsOpenserverClient_withJavaNetSocket_withNSString_(client_, socket, [((JavaNetInetAddress *) nil_chk([((JavaNetSocket *) nil_chk(socket)) getInetAddress])) getHostAddress]);
  [session_ logWithComUsOpenserverLevelEnum:ComUsOpenserverLevelEnum_get_Info() withNSString:NSString_formatWithNSString_withNSObjectArray_(@"Connected to %1$s:%2$s...", [IOSObjectArray newArrayWithObjects:(id[]){ [cfg getHost], JavaLangInteger_valueOfWithInt_([cfg getPort]) } count:2 type:NSObject_class_()])];
  [session_ beginRead];
  return session_;
}

- (void)setSocketOptionsWithJavaNetSocket:(JavaNetSocket *)socket {
  ComUsOpenserverSessionSessionOpener_setSocketOptionsWithJavaNetSocket_(self, socket);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComUsOpenserverClient:", "SessionOpener", NULL, 0x1, NULL, NULL },
    { "connectAsync", NULL, "Lcom.us.openserver.session.Session;", 0x1, "Ljava.lang.Exception;", NULL },
    { "run", NULL, "V", 0x1, NULL, NULL },
    { "connect", NULL, "Lcom.us.openserver.session.Session;", 0x1, "Ljava.lang.Exception;", NULL },
    { "setSocketOptionsWithJavaNetSocket:", "setSocketOptions", "V", 0x2, "Ljava.net.SocketException;", NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "client_", NULL, 0x2, "Lcom.us.openserver.Client;", NULL, NULL,  },
    { "session_", NULL, 0x2, "Lcom.us.openserver.session.Session;", NULL, NULL,  },
    { "exception_", NULL, 0x2, "Ljava.lang.Exception;", NULL, NULL,  },
    { "id__", "id", 0xa, "I", &ComUsOpenserverSessionSessionOpener_id__, NULL,  },
  };
  static const J2ObjcClassInfo _ComUsOpenserverSessionSessionOpener = { 2, "SessionOpener", "com.us.openserver.session", NULL, 0x1, 5, methods, 4, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComUsOpenserverSessionSessionOpener;
}

@end

void ComUsOpenserverSessionSessionOpener_initWithComUsOpenserverClient_(ComUsOpenserverSessionSessionOpener *self, ComUsOpenserverClient *client) {
  (void) NSObject_init(self);
  self->client_ = client;
}

ComUsOpenserverSessionSessionOpener *new_ComUsOpenserverSessionSessionOpener_initWithComUsOpenserverClient_(ComUsOpenserverClient *client) {
  ComUsOpenserverSessionSessionOpener *self = [ComUsOpenserverSessionSessionOpener alloc];
  ComUsOpenserverSessionSessionOpener_initWithComUsOpenserverClient_(self, client);
  return self;
}

void ComUsOpenserverSessionSessionOpener_setSocketOptionsWithJavaNetSocket_(ComUsOpenserverSessionSessionOpener *self, JavaNetSocket *socket) {
  [((JavaNetSocket *) nil_chk(socket)) setSoTimeoutWithInt:[((ComUsOpenserverConfigurationServerConfiguration *) nil_chk([((ComUsOpenserverClient *) nil_chk(self->client_)) getServerConfiguration])) getSocketTimeoutInTicks]];
  [socket setSoLingerWithBoolean:YES withInt:10];
  [socket setTcpNoDelayWithBoolean:YES];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComUsOpenserverSessionSessionOpener)
